avoid deprecated health api - fix rhysd/git-messenger.vim#93
rhysd/git-messenger.vim pull request #94
Opened 2024-08-20 21:40 UTC by woeps

This PR fixes #93: Deprecated (since neovim 0.10) `health#report_*` calls got replaced with `v:lua.vim.health.*` calls.

Tested in neovim 0.11.

2024-08-21 12:01 UTC, rhysd commented
Please ignore CI. The actions used by the CI workflow are too old and it is not related to changes of this PR.

2024-08-21 12:01 UTC, rhysd requested changes

2024-08-22 14:14 UTC, woeps commented
> I've fixed CI. Please rebase this branch onto the latest master branch so that tests can be run properly.

Nice, thanks.
I'll incorporate your suggestions later today.

2024-08-25 20:09 UTC, woeps commented
Sorry for the delay, I hope this is fine now.

2024-08-28 10:52 UTC, rhysd approved these changes
No problem. Thank you for catching this. Merging.

2024-08-28 10:52 UTC, merged